auto: true
server: true

highlighter: rouge
name: James Foster
author: James Foster
title: Move along
description: Nothing to see here
google_analytics: 
show_downloads: false
show_view_on_github: false
theme: jekyll-theme-hacker

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
